export const GET_ALL_USERS = "USERS/GET_ALL";
export const INCREMENT_USER_AGE = "USERS/INCREMENT_USER_AGE";
export const ADD_USER = "USERS/ADD_USER";

export const START_LOADING = "STATUS/START_LOADING";
export const SHOW_SUCCESS = "STATUS/SHOW_SUCCESS";
export const SHOW_ERROR = "STATUS/SHOW_ERROR";
